version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: HealthHub.API/Dockerfile
    ports:
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ConnectionStrings__DefaultConnection=Server=db;Database=HealthHubDB;User=sa;Password=YourStrong!PassW0rd;TrustServerCertificate=True
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - db
    networks:
      - healthhub-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!PassW0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - healthhub-network

volumes:
  sqldata:

networks:
  healthhub-network:
    driver: bridge 