version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: HealthHub.API/Dockerfile
    ports:
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ConnectionStrings__DefaultConnection=Host=db;Database=healthhubdb;Username=postgres;Password=YourStrongPassW0rd
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - db
    networks:
      - healthhub-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrongPassW0rd
      - POSTGRES_DB=healthhubdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthhub-network

volumes:
  postgres_data:

networks:
  healthhub-network:
    driver: bridge 